name: clean-archit-project

services:
  backend:
    build:
      dockerfile: api.dockerfile
      context: .
    image: clean-archit-project-api:latest
    container_name: clean-archit-project-api
    env_file: ./apps/backend/.env
    ports: 
      - "8080:3000"
    restart: unless-stopped

  frontend:
    build:
      dockerfile: web.dockerfile
      context: .
    image: clean-archit-project-web:latest
    container_name: clean-archit-project-web
    ports: 
      - "8081:5173"
    depends_on:
      - backend
    restart: unless-stopped
